### ISSUE TITLE
Out-of-box errors

### ISSUE THREAD

**Issue by danielmarschall** [frdl/oidplus-io4-bridge-plugin#2]
Hallo,

ich habe das Plugin soeben auf dem Testsystem https://hosted.oidplus.com/viathinksoft_dev/ installiert.

Leider funktioniert es nicht.

Beim ersten Aufruf sehe ich folgendes:

```
Warning: Undefined variable $boundary in /daten/homes/oidplus/hosts/hosted.oidplus.com/public_html/webfan.setup.php on line 3083

Warning: filemtime(): stat failed for /daten/homes/oidplus/hosts/hosted.oidplus.com/public_html/webfan.setup.php(1873) : eval()'d code in /daten/homes/oidplus/hosts/hosted.oidplus.com/public_html/webfan.setup.php(1873) : eval()'d code on line 69
Next: The Setup/Installer Chooser App will be installed automatically (global) - The page reloads automatically, please wait ...!
Reloading...
```

nach dem das Installieren abgeschlossen ist   (ist irgendwie schon "creepy", weil ich gar nicht weiß was da für Dinge im Hintergrund installiert werden... aber die Idee, dass man etwas composer-ähnliches nutzt, ohne dass man eine SSH Konsole oder Plesk braucht, finde ich cool)

kommt folgendes:

`Warning: filemtime(): stat failed for /daten/homes/oidplus/hosts/hosted.oidplus.com/public_html/webfan.setup.php(1873) : eval()'d code in /daten/homes/oidplus/hosts/hosted.oidplus.com/public_html/webfan.setup.php(1873) : eval()'d code on line 69`

Diese Warnung kommt auch in ajax.php , weswegen dann auch der jsTreeview nicht funktioniert und das System tot ist...

Es ist wichtig, dass Plugins auch funktionieren, wenn "error reporting" eingeschaltet ist. Das ist immer eine gute Möglichkeit zu sehen, ob das Plugin in Ordnung ist.

----

Seitens PHPstan:

```
 ------ ---------------------------------------------------------------------------------------------------------------------------------------
  Line   plugins/frdl/publicPages/oidplus-io4-bridge-plugin/OIDplusPagePublicIO4.class.php
 ------ ---------------------------------------------------------------------------------------------------------------------------------------
  173    PHPDoc tag @var above a method has no effect.
  173    PHPDoc tag @var does not specify variable name.
  187    Instantiated class Webfan\ComposerAdapter\Installer not found.
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols
  197    Instantiated class Packagist\Api\Client not found.
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols
  363    Class Frdlweb\OIDplus\OIDplusPagePluginRa not found.
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols
  388    Variable $description might not be defined.
  388    Variable $name might not be defined.
  388    Variable $name might not be defined.
  388    Variable $repository might not be defined.
  424    Variable $description might not be defined.
  424    Variable $name might not be defined.
  424    Variable $name might not be defined.
  424    Variable $repository might not be defined.
  459    Variable $description might not be defined.
  459    Variable $name might not be defined.
  459    Variable $name might not be defined.
  459    Variable $repository might not be defined.
  497    Variable $description might not be defined.
  497    Variable $name might not be defined.
  497    Variable $name might not be defined.
  497    Variable $repository might not be defined.
  539    Variable $description might not be defined.
  539    Variable $name might not be defined.
  539    Variable $name might not be defined.
  539    Variable $repository might not be defined.
  575    Variable $description might not be defined.
  575    Variable $name might not be defined.
  575    Variable $name might not be defined.
  575    Variable $repository might not be defined.
  613    Variable $description might not be defined.
  613    Variable $name might not be defined.
  613    Variable $name might not be defined.
  613    Variable $repository might not be defined.
  682    Variable $description might not be defined.
  682    Variable $name might not be defined.
  682    Variable $name might not be defined.
  682    Variable $repository might not be defined.
  723    Variable $description might not be defined.
  723    Variable $name might not be defined.
  723    Variable $name might not be defined.
  723    Variable $repository might not be defined.
  758    Variable $description might not be defined.
  758    Variable $name might not be defined.
  758    Variable $name might not be defined.
  758    Variable $repository might not be defined.
  795    Variable $description might not be defined.
  795    Variable $name might not be defined.
  795    Variable $name might not be defined.
  795    Variable $repository might not be defined.
  1030   Parameter $payload of method Frdlweb\OIDplus\OIDplusPagePublicIO4::loadWebApp() has invalid type Frdlweb\WebAppInterface.
  1030   Parameter $payload of method Frdlweb\OIDplus\OIDplusPagePublicIO4::loadWebApp() has invalid type frdlweb\StubHelperInterface.
  1030   Parameter $payload of method Frdlweb\OIDplus\OIDplusPagePublicIO4::loadWebApp() has invalid type frdlweb\StubRunnerInterface.
  1031   Method Frdlweb\OIDplus\OIDplusPagePublicIO4::loadWebApp() has invalid return type Frdlweb\WebAppInterface.
  1032   Class Frdlweb\WebAppInterface not found.
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols
  1034   Class frdlweb\StubRunnerInterface not found.
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols
  1035   Instantiated class Webfan\AppLauncherWebfatInstaller not found.
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols
  1036   Class frdlweb\StubHelperInterface not found.
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols
  1037   Call to method getRunner() on an unknown class frdlweb\StubHelperInterface.
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols
  1037   Instantiated class Webfan\AppLauncherWebfatInstaller not found.
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols
  1041   Undefined variable: $paylod
  1047   Call to method launch() on an unknown class Frdlweb\WebAppInterface.
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols
  1047   Call to method launch() on an unknown class Webfan\AppLauncherWebfatInstaller.
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols
  1048   Call to method KernelFunctions() on an unknown class Frdlweb\WebAppInterface.
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols
  1048   Call to method KernelFunctions() on an unknown class Webfan\AppLauncherWebfatInstaller.
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols
  1049   Call to method getContainer() on an unknown class Frdlweb\WebAppInterface.
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols
  1049   Call to method getContainer() on an unknown class Webfan\AppLauncherWebfatInstaller.
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols
  1049   Call to method handle() on an unknown class Frdlweb\WebAppInterface.
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols
  1049   Call to method handle() on an unknown class Webfan\AppLauncherWebfatInstaller.
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols
  1050   Class Psr\Http\Message\ResponseInterface not found.
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols
  1051   Call to method emit() on an unknown class Laminas\HttpHandlerRunner\Emitter\SapiEmitter.
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols
  1051   Instantiated class Laminas\HttpHandlerRunner\Emitter\SapiEmitter not found.
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols
  1053   Call to method KernelFunctions() on an unknown class Frdlweb\WebAppInterface.
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols
  1053   Call to method KernelFunctions() on an unknown class Webfan\AppLauncherWebfatInstaller.
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols
  1054   Call to method handleCliRequest() on an unknown class Frdlweb\WebAppInterface.
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols
  1054   Call to method handleCliRequest() on an unknown class Webfan\AppLauncherWebfatInstaller.
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols
  1062   Method Frdlweb\OIDplus\OIDplusPagePublicIO4::getApp() has invalid return type Frdlweb\WebAppInterface.
  1065   Call to method boot() on an unknown class Frdlweb\WebAppInterface.
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols
  1066   Call to method withWebfanWebfatDefaultSettings() on an unknown class Frdlweb\Contract\Autoload\ClassLoaderInterface.
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols
  1071   Method Frdlweb\OIDplus\OIDplusPagePublicIO4::l() has invalid return type Frdlweb\Contract\Autoload\ClassLoaderInterface.
  1072   Call to method getContainer() on an unknown class Frdlweb\WebAppInterface.
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols
  1075   Method Frdlweb\OIDplus\OIDplusPagePublicIO4::c() has invalid return type Psr\Container\ContainerInterface.
  1076   Call to method getContainer() on an unknown class Frdlweb\WebAppInterface.
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols
  1079   Method Frdlweb\OIDplus\OIDplusPagePublicIO4::getContainer() has invalid return type Psr\Container\ContainerInterface.
  1085   Call to method factory() on an unknown class Psr\Container\ContainerInterface.
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols
  1085   Parameter $container of anonymous function has invalid type Psr\Container\ContainerInterface.
  1086   Parameter $route of anonymous function has invalid type League\Route\RouteGroup.
  1088   Call to method map() on an unknown class League\Route\RouteGroup.
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols
  1089   Parameter $request of anonymous function has invalid type Psr\Http\Message\ServerRequestInterface.
  1092   Parameter $container of anonymous function has invalid type Psr\Container\ContainerInterface.
  1098   Instantiated class GuzzleHttp\Psr7\Response not found.
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols
  1099   Call to method withBody() on an unknown class GuzzleHttp\Psr7\Response.
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols
  1099   Call to static method streamFor() on an unknown class GuzzleHttp\Psr7\Utils.
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols
  1106   Call to method map() on an unknown class League\Route\RouteGroup.
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols
  1107   Parameter $request of anonymous function has invalid type Psr\Http\Message\ServerRequestInterface.
  1113   Instantiated class GuzzleHttp\Psr7\Response not found.
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols
  1114   Call to method withBody() on an unknown class GuzzleHttp\Psr7\Response.
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols
  1114   Call to static method streamFor() on an unknown class GuzzleHttp\Psr7\Utils.
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols
  1122   Call to method map() on an unknown class League\Route\RouteGroup.
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols
  1123   Parameter $request of anonymous function has invalid type Psr\Http\Message\ServerRequestInterface.
  1194   Method Frdlweb\OIDplus\OIDplusPagePublicIO4::handle() has invalid return type Psr\Http\Message\ResponseInterface.
  1194   Parameter $request of method Frdlweb\OIDplus\OIDplusPagePublicIO4::handle() has invalid type Psr\Http\Message\ServerRequestInterface.
  1197   Call to method boot() on an unknown class Frdlweb\WebAppInterface.
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols
  1199   Call to method getHeader() on an unknown class Psr\Http\Message\ServerRequestInterface.
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols
  1202   Call to method has() on an unknown class Psr\Container\ContainerInterface.
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols
  1205   Call to method getUri() on an unknown class Psr\Http\Message\ServerRequestInterface.
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols
  1206   Call to method getMethod() on an unknown class Psr\Http\Message\ServerRequestInterface.
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols
  1209   Call to method hasRoute() on an unknown class Frdlweb\WebAppInterface.
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols
  1214   Call to method get() on an unknown class Psr\Container\ContainerInterface.
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols
  1214   Call to method hasRoute() on an unknown class Frdlweb\WebAppInterface.
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols
  1215   Call to method get() on an unknown class Psr\Container\ContainerInterface.
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols
  1216   Call to method getRoute() on an unknown class Frdlweb\WebAppInterface.
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols
  1223   Call to method get() on an unknown class Psr\Container\ContainerInterface.
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols
  1226   Caught class League\Route\Http\Exception\NotFoundException not found.
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols
  1228   Instantiated class GuzzleHttp\Psr7\Response not found.
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols
  1230   Call to method withBody() on an unknown class GuzzleHttp\Psr7\Response.
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols
  1230   Call to static method streamFor() on an unknown class GuzzleHttp\Psr7\Utils.
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols
  1235   Call to method getStatusCode() on an unknown class GuzzleHttp\Psr7\Response.
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols
  1236   Call to method getBody() on an unknown class GuzzleHttp\Psr7\Response.
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols
  1237   Call to method hasRoute() on an unknown class Frdlweb\WebAppInterface.
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols
  1238   Call to method getRoute() on an unknown class Frdlweb\WebAppInterface.
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols
  1246   Instantiated class GuzzleHttp\Psr7\Response not found.
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols
  1247   Call to method withBody() on an unknown class GuzzleHttp\Psr7\Response.
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols
  1248   Call to static method streamFor() on an unknown class GuzzleHttp\Psr7\Utils.
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols
  1254   Instantiated class GuzzleHttp\Psr7\Response not found.
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols
  1255   Call to method withBody() on an unknown class GuzzleHttp\Psr7\Response.
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols
  1255   Call to static method streamFor() on an unknown class GuzzleHttp\Psr7\Utils.
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols
  1258   Instantiated class GuzzleHttp\Psr7\Response not found.
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols
  1259   Call to method withBody() on an unknown class GuzzleHttp\Psr7\Response.
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols
  1259   Call to static method streamFor() on an unknown class GuzzleHttp\Psr7\Utils.
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols
  1274   Call to method getResponseHeader() on an unknown class Frdlweb\WebAppInterface.
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols
  1278   Access to property $Document on an unknown class Frdlweb\WebAppInterface.
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols
  1279   Call to static method streamFor() on an unknown class GuzzleHttp\Psr7\Utils.
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols
  1297   Instantiated class GuzzleHttp\Psr7\Response not found.
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols
  1298   Call to method withBody() on an unknown class GuzzleHttp\Psr7\Response.
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols
  1298   Call to static method streamFor() on an unknown class GuzzleHttp\Psr7\Utils.
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols
  1308   Call to method emit() on an unknown class Laminas\HttpHandlerRunner\Emitter\SapiEmitter.
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols
  1308   Instantiated class Laminas\HttpHandlerRunner\Emitter\SapiEmitter not found.
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols
  1310   Class Psr\Http\Message\ResponseInterface not found.
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols
  1311   Call to method getStatusCode() on an unknown class Psr\Http\Message\ResponseInterface.
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols
  1314   Call to method emit() on an unknown class Laminas\HttpHandlerRunner\Emitter\SapiEmitter.
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols
  1314   Instantiated class Laminas\HttpHandlerRunner\Emitter\SapiEmitter not found.
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols
  1319   Unreachable statement - code above always terminates.
  1321   Call to method getStatusCode() on an unknown class Psr\Http\Message\ResponseInterface.
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols
  1322   Call to method emit() on an unknown class Laminas\HttpHandlerRunner\Emitter\SapiEmitter.
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols
  1322   Instantiated class Laminas\HttpHandlerRunner\Emitter\SapiEmitter not found.
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols
  1324   Unreachable statement - code above always terminates.
  1327   Call to method emit() on an unknown class Laminas\HttpHandlerRunner\Emitter\SapiEmitter.
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols
  1327   Instantiated class Laminas\HttpHandlerRunner\Emitter\SapiEmitter not found.
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols
  1329   Unreachable statement - code above always terminates.
  1466   Method Frdlweb\OIDplus\OIDplusPagePublicIO4::schema_read_cache() should return array|null but returns bool|object.
  1469   Method Frdlweb\OIDplus\OIDplusPagePublicIO4::schema_read_cache() should return array|null but returns false.
  1726   Method Frdlweb\OIDplus\OIDplusPagePublicIO4::restApiCall() should return array|false but return statement is missing.
  1751   Call to an undefined method ViaThinkSoft\OIDplus\OIDplusObject::isConfidental().
 ------ ---------------------------------------------------------------------------------------------------------------------------------------

 ------ ---------------------------------------------------------------------------
  Line   plugins/frdl/publicPages/oidplus-io4-bridge-plugin/autoloader.php
 ------ ---------------------------------------------------------------------------
  24     Function IO4\_installClass() has parameter $class with no type specified.
 ------ ---------------------------------------------------------------------------

```

**Comment by danielmarschall** [comment]
Nachtrag:

Das Aufrufen von cronjob.sh zeigt folgendes:

```
Warning: file_put_contents(/webfan.setup.php): Failed to open stream: Permission denied in /daten/homes/oidplus/lib/classes/Webfan/Webfat/getWebfatTrait.php on line 50

Warning: require_once(/webfan.setup.php): Failed to open stream: No such file or directory in /daten/homes/oidplus/lib/classes/Webfan/Webfat/getWebfatTrait.php on line 55

Fatal error: Uncaught Error: Failed opening required '/webfan.setup.php' (include_path='.:/usr/share/php') in /daten/homes/oidplus/lib/classes/Webfan/Webfat/getWebfatTrait.php:55
Stack trace:
#0 /daten/homes/oidplus/hosts/hosted.oidplus.com/public_html/viathinksoft_dev/plugins/frdl/publicPages/oidplus-io4-bridge-plugin/OIDplusPagePublicIO4.class.php(998): IO4\Webfat->getWebfat()
#1 /daten/homes/oidplus/hosts/hosted.oidplus.com/public_html/viathinksoft_dev/plugins/frdl/publicPages/oidplus-frdlweb-rdap/OIDplusPagePublicRdap.class.php(516): Frdlweb\OIDplus\OIDplusPagePublicIO4->getWebfat()
#2 /daten/homes/oidplus/hosts/hosted.oidplus.com/public_html/viathinksoft_dev/includes/classes/OIDplus.class.php(1351): Frdlweb\OIDplus\OIDplusPagePublicRdap->init()
#3 /daten/homes/oidplus/hosts/hosted.oidplus.com/public_html/viathinksoft_dev/cron.sh(31): ViaThinkSoft\OIDplus\OIDplus::init()
#4 {main}
  thrown in /daten/homes/oidplus/lib/classes/Webfan/Webfat/getWebfatTrait.php on line 55
```



![image](https://github.com/frdl/oidplus-io4-bridge-plugin/assets/28412477/c9828e07-68f9-45d3-ad5b-4fa7a3486971)

**Comment by danielmarschall** [comment]
Noch eine Kleinigkeit:

Habe jetzt gerade nochmal ein Update von io4 und rdap gemacht, und der Cronjob (Console CLI) ist gelaufen, bevor ich über den Browser rein bin.

Dann stand in der Ausgabe der konsole:

```
Warning: Undefined variable $boundary in /daten/homes/oidplus/hosts/hosted.oidplus.com/public_html/viathinksoft_dev/webfan.setup.php on line 3083

Warning: filemtime(): stat failed for /daten/homes/oidplus/hosts/hosted.oidplus.com/public_html/viathinksoft_dev/webfan.setup.php(1873) : eval()'d code in /daten/homes/oidplus/hosts/hosted.oidplus.com/public_html/viathinksoft_dev/webfan.setup.php(1873) : eval()'d code on line 69

Warning: Undefined array key "REQUEST_METHOD" in /daten/homes/oidplus/hosts/hosted.oidplus.com/public_html/viathinksoft_dev/webfan.setup.php on line 825
<h1 style="color:green;">Next: The Setup/Installer Chooser App will be installed automatically (global) - The page reloads automatically, please wait ...!</h1><form id="idr777777777777777777777717139726038888883830939037" action="" method=""></form><p class="btn-info" style="color:red;background:url(https://io4.xyz.webfan3.de/assets/ajax-loader_2.gif) no-repeat;">Reloading...</p><script>(()=>{setTimeout(()=>{document.getElementById('idr777777777777777777777717139726038888883830939037').submit();}, 10000)})();</script>
```

--> hier solltest du vielleicht drauf achten, dass HTML ausgaben nur kommen, wenn der Benutzer über den Browser reingeht. Wenn es über den Cronjob passiert soll kein HTML ausgegeben werden. Außerdem muss darauf geachtet werden, dass beim CLI-Cronjob das Feld "REQUEST_METHOD" in $_SERVER nicht gesetzt ist.
